[package]
name = "rust_lib_flutter_rust_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.40"
zsign = { path = "/Users/lake/dounine/github/rust/rust-zsign", version = "0.0.18" }